[project]
name        = 'rx_misid'
description = 'Project used to calculate fully hadronic misid shapes'
version     = '0.0.1'
readme      = 'README.md'
dependencies= [
'data_manipulation_utilities>0.1.2',
'PyYAML',
'rx_data',
'pyarrow',
'boost-histogram',
'rx_selection',
]

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[tool.setuptools.package-data]
'rx_misid_data' = ['*.yaml']
