# Particles charges are defined from AP's YAML config:
# https://gitlab.cern.ch/lhcb-datapkg/AnalysisProductions/-/blob/223655c72f9c778cf9daa9a0138174b464ac7ca9/rd_ap_2024/tupling/config/b_to_xll_mva.yaml

input :
  trigger  : Hlt2RD_BuToKpEE_MVA
  selection:
    bdt : mva_cmb > 0.5 && mva_prc > 0.5
weights : &mp
  path : /home/acampove/external_ssd/Calibration/mis_id/v2
  regions: # These are cuts that need to appear in the name of the pkl files with the PID maps
    control : (PROBNN_E<0.2|DLLe<3)&(DLLe>1.0)
    signal  : (PROBNN_E>0.2)&(DLLe>3.0)
  pars :
    - TRACK_P
    - TRACK_ETA
splitting:
  observable: B_M_brem_track_2
  tracks: # This is needed to assign the right electrons to PassFail, FailPass ... datasets
    ss : L1 # Lepton with same charge as B
    os : L2 # Lepton with opposite charge as B
  hadron_tagging:
    kaon :  LEP_PROBNN_K > 0.1
    pion :  LEP_PROBNN_K < 0.1
  lepton_tagging:
    #pass :  LEP_PROBNN_E > 0.2 && LEP_PID_E > 3
    #fail : (LEP_PROBNN_E < 0.2 || LEP_PID_E < 3) && LEP_PID_E > 1
    pass :  LEP_PROBNN_E > 0.5 && LEP_PID_E > 4
    fail : (LEP_PROBNN_E < 0.5 || LEP_PID_E < 4) && LEP_PID_E > 1
  maps:
    <<: *mp
